import { Options } from "../types";
import { resolveEnvExample } from "../../../shared/resolve-env-example";

const createDeclaration = (options: Options) => {
  const envExampleKeys = resolveEnvExample({
    envExampleFilePath: options.example,
  });
  return [
    "// Generated by '@import-meta-env/flow'",
    "",
    "declare type Import$Meta = {",
    "  +env: $ReadOnly<{",
    ...envExampleKeys.map((key) => `    ${key}: string,`),
    "  }>,",
    "};",
    "",
  ].join("\n");
};

export default createDeclaration;
