import { Options } from "../types";
import { parseEnvExampleKeys } from "./parse-env-example-keys";

const createDeclaration = (options: Options) => {
  const envExampleKeys = parseEnvExampleKeys(options.example);
  return [
    "// Generated by '@import-meta-env/flow'",
    "",
    "declare type Import$Meta = {",
    "  +env: $ReadOnly<{",
    ...envExampleKeys.map((key) => `    ${key}: string,`),
    "  }>,",
    "};",
    "",
  ].join("\n");
};

export default createDeclaration;
