import { Options } from "../types";
import { resolveEnvExampleKeys } from "../../../shared/resolve-env-example-keys";

const createDeclaration = (options: Options) => {
  const envExampleKeys = resolveEnvExampleKeys({
    envExampleFilePath: options.example,
  });
  return [
    "// Generated by '@import-meta-env/typescript'",
    "",
    "interface ImportMetaEnv {",
    ...envExampleKeys.map((key) => `  readonly ${key}: string;`),
    "}",
    "",
    "interface ImportMeta {",
    "  readonly env: ImportMetaEnv;",
    "}",
    "",
  ].join("\n");
};

export default createDeclaration;
